services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      DIFFICULTY: "normal"
      ENABLE_ROLLING_LOGS: "TRUE"
      EULA: "TRUE"
      MEMORY: "15G"
      ONLINE_MODE: "TRUE"
      SEED: "7515057474427670726"
      SNOOPER_ENABLED: "FALSE"
      TYPE: FABRIC
      TZ: "Asia/Kolkata"
      USE_AIKAR_FLAGS: "TRUE"
      VERSION: "1.21.5"
#https://github.com/LuckPerms/LuckPerms/issues/4083#issuecomment-2885020158
      MODRINTH_PROJECTS: |
        fabric-api
        tabtps
        lithium
        ferrite-core
        krypton
        visible-traders
        luckperms:v5.4.158-fabric
    volumes:
      - ./data:/data
  backups:
    image: itzg/mc-backup
    environment:
      BACKUP_INTERVAL: "2h"
      PRUNE_BACKUPS_DAYS: 2
      RCON_HOST: mc
      TZ: "Asia/Kolkata"
    volumes:
      - ./data:/data:ro
      - ./mc-backups:/backups
